#ifndef QAZURESTORAGERESTAPI_GLOBAL_H
#define QAZURESTORAGERESTAPI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QAZURESTORAGERESTAPI_LIBRARY)
#  define QAZURESTORAGERESTAPISHARED_EXPORT Q_DECL_EXPORT
#else
#  define QAZURESTORAGERESTAPISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QAZURESTORAGERESTAPI_GLOBAL_H
